import { AppConfig } from './types'

export const DEFAULT_CONFIG: AppConfig = {
  apiConfigs: [],
  modelRoutes: [],
  characters: [
    {
      id: 'default',
      name: '默认助手',
      systemPrompt: '你是一个友好的 AI 助手，帮助用户高效完成任务。',
      greeting: '你好，我是你的 AI 助手。有什么我可以帮你？',
    },
  ],
  activeCharacterId: 'default',
  hotkeys: {
    toggleChat: 'CommandOrControl+Shift+A',
    toggleLive2D: 'CommandOrControl+Shift+L',
  },
  watchFolders: [],
  randomTimerRange: { min: 30, max: 120 },
  triggerPrompts: {
    hotkey: '用户通过快捷键唤起了你，请简短问候并询问需求。',
    click_avatar: '用户点击了你的形象，请给出自然、简短的回应。',
    random_timer: '请主动发起一段轻量对话，可以是提醒、建议或简短闲聊。',
    file_change: '监听目录发生文件变动：{{fileChangeInfo}}。请告知用户并询问是否需要处理。',
    text_input: '',
  },
  live2dModelPath: '',
  live2dActionMap: {
    expression: {},
    motion: {},
  },
  webSearch: {
    allowDomains: [],
    blockDomains: [],
  },
  agentChain: {
    enableAutoTaskRouting: true,
    taskClassifierRules: [
      {
        id: 'task-rule-vision',
        name: '视觉任务',
        pattern: '![.*]\\(.*\\)|https?:\\/\\/\\S+\\.(png|jpg|jpeg|webp|gif)|data:image\\/[a-z+]+;base64,|识别图片|图里|看图|图像|ocr|image',
        taskType: 'vision',
        enabled: true,
        priority: 1,
      },
      {
        id: 'task-rule-translation',
        name: '翻译任务',
        pattern: '翻译|translate|译为',
        taskType: 'translation',
        enabled: true,
        priority: 2,
      },
      {
        id: 'task-rule-summary',
        name: '总结任务',
        pattern: '总结|摘要|归纳|总结一下',
        taskType: 'summary',
        enabled: true,
        priority: 3,
      },
      {
        id: 'task-rule-file',
        name: '文件操作',
        pattern: '读取文件|写入文件|文件夹|目录|path|\\.txt|\\.md|\\.json',
        taskType: 'file_operation',
        enabled: true,
        priority: 4,
      },
      {
        id: 'task-rule-roleplay',
        name: '角色扮演',
        pattern: '扮演|角色扮演|你现在是|请你饰演',
        taskType: 'roleplay',
        enabled: true,
        priority: 5,
      },
      {
        id: 'task-rule-tool',
        name: '工具调用',
        pattern: '调用工具|使用工具|tool',
        taskType: 'tool_call',
        enabled: true,
        priority: 6,
      },
    ],
    enableContextCompression: true,
    compressionThresholdTokens: 3200,
    compressionKeepRecentMessages: 12,
    enableMemory: true,
    memoryTopK: 6,
    memoryMinScore: 0.22,
    memoryDeduplicate: true,
    memoryMaxItems: 500,
  },
  window: {
    chatWidth: 400,
    chatHeight: 600,
    live2dWidth: 300,
    live2dHeight: 400,
  },
}
